baseURL = "https://7und3dpy.github.io/website/"
theme = ["hugo-coder"]
languageCode = "en"
defaultContentLanguage = "en"
paginate = 20
enableEmoji = true

    
[markup.highlight]
noClasses = false

defaultContentLanguageInSubdir = true
[languages]
    [languages.en]
    languageName = ":uk:"
    title = "Turio"
    contentDir = "content/en"
    disable = false
        [languages.en.params]
        author = "Turio"
        description = "Turio's personal website"
        keywords = "blog, researcher, developer,personal"
        info = ["Cyber Security Student"]
        avatarURL = "images/chandung.jpg"


        # Git Commit in Footer, uncomment the line below to enable it
        #commit = "https://github.com/luizdepra/hugo-coder/tree/"
        # Right To Left, shift content direction for languagues such as Arabic
        rtl = false
        # Specify light/dark colorscheme
        #Supported values:
        #"auto" (use preference set by browser)
        #"dark" (dark background, light foreground)
        #"light" (light background, dark foreground) (default)
        colorScheme = "dark"
        # Hide the toggle button, along with the associated vertical divider
        hideColorSchemeToggle = false
        # Series see also post count
        maxSeeAlsoItems = 4
        # Custom CSS
        customCSS = []
        # Custom SCSS, file path is relative to Hugo's asset folder (default: {your project root}/assets)
        customSCSS = []

        # Custom JS
        customJS = []

        # Custom remote JS files
        customRemoteJS = []


        [taxonomies]
        category = "categories"
        series = "series"
        tag = "tags"
        author = "authors"

        [[params.social]]
        name = "Github"
        icon = "fa fa-2x fa-github"
        weight = 1
        url = "https://github.com/7und3dpy"

        [[params.social]]
        name = "Gitlab"
        icon = "fa fa-2x fa-gitlab"
        weight = 2
        url = "https://gitlab.com/7und3dpy"


        [[params.social]]
        name = "LinkedIn"
        icon = "fa fa-2x fa-linkedin"
        weight = 3
        url = "https://www.linkedin.com/in/minhtuan88/"



        [[languages.en.menu.main]]
        name = "About"
        weight = 1
        url = "about/"

        [[languages.en.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"

        [[languages.en.menu.main]]
        name = "Projects"
        weight = 3
        url = "projects/"

        [[languages.en.menu.main]]
        name = "Contact me"
        weight = 5
        url = "contact/"

        #-------------------------------------------------------------------#

    [languages.vi]
    languageName = ":vietnam:"
    contentDir = "content/vn"
    title = "Trần Minh Tuấn"

        [languages.vi.params]
        author = "Trần Minh Tuấn"
        avatarURL = "images/chandung.jpg"
        info = "Sinh viên ngành An Toàn Thông Tin"

        keywords = "Blog, Nghiên cứu, Phát triển, Sở thích cá nhân"

        [[languages.vi.menu.main]]
        name = "Về tôi"
        weight = 1
        url = "about/"

        [[languages.vi.menu.main]]
        name = "Blog"
        weight = 2
        url = "posts/"

        [[languages.vi.menu.main]]
        name = "Các dự án"
        weight = 3
        url = "projects/"

        [[languages.vi.menu.main]]
        name = "Liên lạc"
        weight = 4
        url = "contact/"
